// ============================================
// 商業數位導航站 - 數據層
// ============================================

// === 四大方案定義 ===
export const solutionPlans = [
    {
        id: "A",
        name: "極速獲客型",
        subtitle: "一頁式網站 Landing Page",
        shortDesc: "結構簡單、資訊集中、載入速度快",
        description: "專為「緊急需求」或「在地服務」業者設計。重點在於「行動呼籲 (Call to Action)」，如直接撥打電話或加 Line。",
        targetAudience: ["居家清潔", "水電維修", "搬家公司", "除蟲公司", "冷氣清洗"],
        sellingPoints: [
            "只需一天即可上線接單",
            "專為手機瀏覽設計，客戶一點擊就能聯絡您",
            "預算低，適合剛創業或想投放廣告測試市場的老闆",
        ],
        features: [
            "5 秒極速載入技術",
            "手機最佳化設計",
            "Google 地圖整合",
            "一鍵撥號功能",
            "LINE 官方帳號串接",
        ],
        icon: "Rocket",
        gradient: "from-emerald-400 to-teal-500",
        color: "emerald",
    },
    {
        id: "B",
        name: "品牌形象型",
        subtitle: "官方網站 Corporate Website",
        shortDesc: "多頁面架構，強調專業形象與信任感",
        description: "多頁面架構，強調「關於我們」、「服務流程」、「案例展示 (Portfolio)」。設計感較強，重視信任感的建立。",
        targetAudience: ["室內設計", "建築公司", "律師事務所", "顧問公司", "B2B 傳產工廠"],
        sellingPoints: [
            "讓您的報價比同業高 20% 的秘密——專業的品牌形象",
            "完整的案例展示系統，讓作品集為您說話",
            "建立客戶信任感，縮短成交猶豫期",
        ],
        features: [
            "多頁面專業架構",
            "案例作品集展示",
            "服務流程說明",
            "關於我們品牌故事",
            "聯繫表單整合",
        ],
        icon: "Building2",
        gradient: "from-amber-400 to-orange-500",
        color: "amber",
    },
    {
        id: "C",
        name: "智慧預約型",
        subtitle: "管理系統網站 Booking System",
        shortDesc: "整合行事曆、時段選擇、會員管理",
        description: "整合行事曆、時段選擇、會員管理。核心價值在於「節省人力成本」與「24小時自動接單」。",
        targetAudience: ["美甲美睫", "美容 SPA", "推拿整復", "健身教練", "心理諮商", "診所"],
        sellingPoints: [
            "半夜也能自動接單，不錯過任何一位想預約的客人",
            "告別紙本登記與 Line 來回確認時間的混亂",
            "自動發送預約提醒，降低客戶放鳥率",
        ],
        features: [
            "線上預約系統",
            "自動化訂單管理",
            "客戶資料庫建立",
            "LINE 推播通知",
            "數據分析儀表板",
        ],
        icon: "Calendar",
        gradient: "from-violet-400 to-purple-500",
        color: "violet",
    },
    {
        id: "D",
        name: "電商銷售型",
        subtitle: "線上開店網站 E-commerce",
        shortDesc: "完整購物車、金流物流串接、商品管理",
        description: "完整的購物車、金流串接 (信用卡/行動支付)、物流設定、商品管理後台。擁有自己的會員名單，不再被平台抽成。",
        targetAudience: ["食品伴手禮", "服飾品牌", "團購主", "單一產品品牌商", "文創商品"],
        sellingPoints: [
            "擁有自己的會員名單，不再被平台 (如蝦皮/Momo) 抽高額手續費",
            "品牌專屬風格，提升產品溢價能力",
            "完整的後台數據，讓您知道誰是忠實顧客",
        ],
        features: [
            "購物車系統",
            "金流串接（信用卡/行動支付）",
            "物流整合",
            "商品管理後台",
            "會員訂單追蹤",
        ],
        icon: "ShoppingCart",
        gradient: "from-pink-400 to-rose-500",
        color: "pink",
    },
];

// === 作品案例 ===
export const portfolioCases = [
    {
        id: 1,
        name: "潔淨管家 Turbo Clean",
        category: "極速獲客型",
        industry: "居家服務",
        url: "https://fir-1-ad84c.web.app/",
        description: "專業清潔服務品牌形象網站，快速建立可信度",
        planType: "A",
        tags: ["一鍵撥號", "LINE整合", "手機優化"],
        gradient: "from-cyan-500 to-blue-500",
        icon: "Sparkles",
        image: "/images/demo-turbo-clean.jpg",
    },
    {
        id: 2,
        name: "匠心設計｜輕裝修美學",
        category: "品牌形象型",
        industry: "室內設計",
        url: "https://webwork-dbde9.web.app/",
        description: "透明報價系統，36萬起45天入住的輕裝修專家",
        planType: "B",
        tags: ["報價系統", "案例展示", "專業形象"],
        gradient: "from-amber-500 to-orange-500",
        icon: "Palette",
        image: "/images/demo-craftsman-design.jpg",
    },
    {
        id: 3,
        name: "爆爆花桶",
        category: "電商銷售型",
        industry: "電商零售",
        url: "https://fir-1-16528.web.app/",
        description: "創意禮品電商，打造獨特的送禮體驗",
        planType: "D",
        tags: ["購物車", "產品展示", "訂單管理"],
        gradient: "from-pink-500 to-rose-500",
        icon: "Gift",
        image: "/images/demo-boom-flower.jpg",
    },
    {
        id: 4,
        name: "極淨專業冷氣清洗",
        category: "極速獲客型",
        industry: "居家服務",
        url: "https://fir-4-9a890.web.app/",
        description: "大台北地區專業到府服務，價格透明絕不加價",
        planType: "A",
        tags: ["價格透明", "一鍵預約", "SOP服務"],
        gradient: "from-emerald-500 to-teal-500",
        icon: "Wind",
        image: "/images/demo-ac-cleaning.png",
    },
    {
        id: 5,
        name: "LUNA Fashion Nail",
        category: "智慧預約型",
        industry: "美業沙龍",
        url: "https://fir-5-a43a7.web.app/",
        description: "智慧預約系統，24小時自動接單管理",
        planType: "C",
        tags: ["線上預約", "會員管理", "自動通知"],
        gradient: "from-violet-500 to-purple-500",
        icon: "Calendar",
        image: "/images/demo-luna-nail.jpg",
    },
    {
        id: 6,
        name: "綠研生醫 Nature Lab",
        category: "智慧預約型",
        industry: "保健食品",
        url: "https://fir-7-8ae24.web.app/",
        description: "專利植萃品牌，中西醫博士聯手研發",
        planType: "C",
        tags: ["品牌形象", "產品展示", "信任背書"],
        gradient: "from-green-500 to-emerald-500",
        icon: "Leaf",
        image: "/images/demo-nature-lab.png",
    },
];

// === 案例分類（按方案類型） ===
export const portfolioCategories = [
    { id: "all", name: "全部案例", icon: "LayoutGrid" },
    { id: "A", name: "極速獲客型", icon: "Rocket" },
    { id: "B", name: "品牌形象型", icon: "Building2" },
    { id: "C", name: "智慧預約型", icon: "Calendar" },
    { id: "D", name: "電商銷售型", icon: "ShoppingCart" },
];

// === 首屏內容 ===
export const heroContent = {
    headline: "別讓您的生意，在網路上「隱形」。",
    subheadline: "用最聰明的方式，打造您的 24 小時自動化店面。",
    description: "不懂技術？預算有限？沒關係。我們運用最新 AI 雲端架構，為您省下 50% 開發成本，換來 3 倍的運營效率。不綁架程式碼，只專注為您賺錢。",
    ctaText: "免費診斷：30 秒找出適合您的賺錢模式",
    ctaSubtext: "已有 500+ 老闆完成診斷",
};

// === 診斷問題（支援 A/B/C/D 四種方案） ===
export const diagnosisQuestions = [
    {
        id: 1,
        question: "關於您的生意現狀，最讓您頭痛的是什麼？",
        subtext: "選擇最符合您情況的選項",
        options: [
            {
                id: "1a",
                text: "沒人知道我",
                description: "我想讓客人在 Google 地圖上找得到我，打電話給我。",
                scores: { A: 3, B: 1, C: 0, D: 0 },
                icon: "Search",
            },
            {
                id: "1b",
                text: "回訊息回到手軟",
                description: "預約很亂、漏單，我需要有人幫我自動接單。",
                scores: { A: 0, B: 0, C: 3, D: 0 },
                icon: "MessageSquare",
            },
            {
                id: "1c",
                text: "很難展現專業價值",
                description: "客戶覺得我跟別人沒兩樣，比價比很兇。",
                scores: { A: 0, B: 3, C: 0, D: 0 },
                icon: "Award",
            },
            {
                id: "1d",
                text: "想賣商品但被平台抽成",
                description: "在蝦皮/Momo 賣東西抽成太高，想有自己的店。",
                scores: { A: 0, B: 0, C: 0, D: 3 },
                icon: "ShoppingBag",
            },
        ],
    },
    {
        id: 2,
        question: "對於「數位店面」，您目前的預算與心態是？",
        subtext: "誠實回答，我們為您量身推薦",
        options: [
            {
                id: "2a",
                text: "小本經營 / 剛創業",
                description: "想先用最低成本試水溫，有效再升級。",
                scores: { A: 3, B: 0, C: 0, D: 0 },
                icon: "Sprout",
            },
            {
                id: "2b",
                text: "生意穩定，願意投資",
                description: "只要能幫我省下人力成本就好。",
                scores: { A: 0, B: 1, C: 3, D: 1 },
                icon: "TrendingUp",
            },
            {
                id: "2c",
                text: "預算不是問題",
                description: "重點是要看起來夠專業，功能要能解決複雜需求。",
                scores: { A: 0, B: 3, C: 1, D: 2 },
                icon: "Crown",
            },
            {
                id: "2d",
                text: "想建立品牌電商",
                description: "願意投資打造自己的線上商店。",
                scores: { A: 0, B: 0, C: 0, D: 3 },
                icon: "Store",
            },
        ],
    },
    {
        id: 3,
        question: "您希望這個網站上線後，發生什麼事？",
        subtext: "選擇您最期待的結果",
        options: [
            {
                id: "3a",
                text: "電話開始響，有人加我的 LINE",
                description: "快速獲得曝光與客戶詢問",
                scores: { A: 3, B: 1, C: 0, D: 0 },
                icon: "Phone",
            },
            {
                id: "3b",
                text: "睡覺時也能收到預約單",
                description: "自動化接單，解放雙手",
                scores: { A: 0, B: 0, C: 3, D: 0 },
                icon: "Moon",
            },
            {
                id: "3c",
                text: "客戶覺得我超專業，主動留資料諮詢",
                description: "建立權威形象，吸引高價值客戶",
                scores: { A: 0, B: 3, C: 0, D: 0 },
                icon: "Star",
            },
            {
                id: "3d",
                text: "有人直接下單付款買我的商品",
                description: "完整購物流程，躺著收訂單",
                scores: { A: 0, B: 0, C: 0, D: 3 },
                icon: "CreditCard",
            },
        ],
    },
];

// === 方案結果（四種方案） ===
export const planResults = {
    A: {
        id: "A",
        title: "極速獲客型",
        subtitle: "一頁式網站 Landing Page",
        tagline: "最快變現的選擇",
        analysis: `經分析，您的生意正處於「曝光紅利期」。現在花大錢做複雜系統是浪費，您真正需要的是一個「極速載入、手機優先」的導流入口。讓客人在 3 秒內找到您、撥通電話，這才是最快變現的方式。`,
        features: [
            "5 秒極速載入技術",
            "手機最佳化設計",
            "Google 地圖整合",
            "一鍵撥號功能",
            "LINE 官方帳號串接",
        ],
        targetAudience: ["居家清潔", "水電維修", "搬家公司", "除蟲公司"],
        sellingPoints: [
            "只需一天即可上線接單",
            "專為手機瀏覽設計，客戶一點擊就能聯絡您",
            "預算低，適合剛創業或想投放廣告測試市場的老闆",
        ],
        marketPrice: "$40,000+",
        yourPrice: "$26,800",
        priceNote: "起",
        valueProposition: "一天不到 $20 元的主機維護，比印傳單還划算。",
        usageScenarios: [
            { icon: "User", actor: "客人小王", action: "在 Google 搜尋「居家清潔」或「冷氣清洗」" },
            { icon: "MapPin", actor: "發現您的網站", action: "手機上 3 秒就能查看服務與價格" },
            { icon: "Phone", actor: "直接點擊", action: "「立即撥號」按鈕，30 秒內成交！" },
        ],
        demoName: "極淨專業冷氣清洗",
        demoUrl: "https://fir-4-9a890.web.app",
        color: "from-emerald-400 to-teal-500",
        icon: "Rocket",
    },
    B: {
        id: "B",
        title: "品牌形象型",
        subtitle: "官方網站 Corporate Website",
        tagline: "彰顯專業的選擇",
        analysis: `經分析，您販售的是「專業與信任」。一般的套版網站配不上您的專業。我們將為您打造多頁面的品牌官網，完整展示您的案例作品集、服務流程與品牌故事，讓高單價客戶主動找上門。`,
        features: [
            "多頁面專業架構",
            "案例作品集展示",
            "服務流程說明",
            "關於我們品牌故事",
            "聯繫表單整合",
        ],
        targetAudience: ["室內設計", "建築公司", "律師事務所", "顧問公司"],
        sellingPoints: [
            "讓您的報價比同業高 20% 的秘密——專業的品牌形象",
            "完整的案例展示系統，讓作品集為您說話",
            "建立客戶信任感，縮短成交猶豫期",
        ],
        marketPrice: "$150,000+",
        yourPrice: "$68,000",
        priceNote: "起",
        valueProposition: "這是您數位形象的護城河，別人抄不走。",
        usageScenarios: [
            { icon: "User", actor: "高价客户", action: "通过互联网搜索室内设计，看到您的网站" },
            { icon: "Briefcase", actor: "浏览您的作品集", action: "被作品质感打动，開始信任您" },
            { icon: "MessageSquare", actor: "主动填写表单", action: "留下联系方式，约谈见面！" },
        ],
        demoName: "匠心設計｜輕裝修美學",
        demoUrl: "https://webwork-dbde9.web.app",
        color: "from-amber-400 to-orange-500",
        icon: "Building2",
    },
    C: {
        id: "C",
        title: "智慧預約型",
        subtitle: "管理系統網站 Booking System",
        tagline: "省時省力的選擇",
        analysis: `經分析，您的時間價值極高，不該浪費在重複的溝通上。您不需要請工讀生，您需要的是一套「24 小時自動接單系統」。這套系統擁有像 App 一樣流暢的體驗，客人自己預約、自己下單，您只要負責收錢就好。`,
        features: [
            "線上預約系統",
            "自動化訂單管理",
            "客戶資料庫建立",
            "LINE 推播通知",
            "數據分析儀表板",
        ],
        targetAudience: ["美甲美睫", "美容 SPA", "推拿整復", "健身教練"],
        sellingPoints: [
            "半夜也能自動接單，不錯過任何一位想預約的客人",
            "告別紙本登記與 Line 來回確認時間的混亂",
            "自動發送預約提醒，降低客戶放鳥率",
        ],
        marketPrice: "$1,000,000+",
        marketPriceNote: "（做 App 行情）",
        yourPrice: "$58,000",
        priceNote: "起",
        valueProposition: "一次買斷，終身無抽成，兩年省下的抽成費就回本了。",
        demoName: "LUNA Fashion Nail 美甲沙龍",
        demoUrl: "https://fir-5-a43a7.web.app",
        color: "from-violet-400 to-purple-500",
        icon: "Calendar",
    },
    D: {
        id: "D",
        title: "電商銷售型",
        subtitle: "線上開店網站 E-commerce",
        tagline: "擁有自己品牌的選擇",
        analysis: `經分析，您需要的是一個「品牌專屬電商」。不用再被平台抽成，完整的購物車、金流串接、物流整合，讓您擁有自己的會員名單，建立長期客戶關係，提升產品溢價能力。`,
        features: [
            "購物車系統",
            "金流串接（信用卡/行動支付）",
            "物流整合",
            "商品管理後台",
            "會員訂單追蹤",
        ],
        targetAudience: ["食品伴手禮", "服飾品牌", "團購主", "文創商品"],
        sellingPoints: [
            "擁有自己的會員名單，不再被平台抽高額手續費",
            "品牌專屬風格，提升產品溢價能力",
            "完整的後台數據，讓您知道誰是忠實顧客",
        ],
        marketPrice: "$500,000+",
        marketPriceNote: "（電商系統客製行情）",
        yourPrice: "$88,000",
        priceNote: "起",
        valueProposition: "自己的電商自己經營，會員名單就是您最大的資產。",
        demoName: "爆爆花桶 創意禮品",
        demoUrl: "https://fir-1-16528.web.app",
        color: "from-pink-400 to-rose-500",
        icon: "ShoppingCart",
    },
};

// === 信任背書 ===
export const trustSignals = [
    {
        id: 1,
        title: "快速交付，搶先上線",
        description: "我們專注效率，最快 3 天即可讓您的網站上線營業。時間就是金錢，讓您比同業更早搶佔市場先機，開始接單賺錢。",
        icon: "Zap",
        highlight: "最快 3 天上線",
    },
    {
        id: 2,
        title: "優惠價格，透明報價",
        description: "我們提供業界最具競爭力的價格，報價一目瞭然，絕無隱藏費用。讓您用最划算的預算，打造最專業的數位門面。",
        icon: "BadgePercent",
        highlight: "業界最優惠價格",
    },
    {
        id: 3,
        title: "專業售後，長期陪伴",
        description: "網站上線後我們持續提供技術支援與諮詢服務。任何問題隨時找我們，讓您無後顧之憂，專心經營您的事業。",
        icon: "HeadphonesIcon",
        highlight: "終身技術支援",
    },
];

// === 公司資訊 ===
export const companyInfo = {
    name: "anting studio",
    tagline: "用 AI 為您的生意賦能",
    email: "anting13579@gmail.com",
    phone: "0930693088",
    copyright: "© 2024 anting studio. All rights reserved.",
};

// === 名單收集表單 ===
export const leadCaptureContent = {
    title: "即將為您呈現專屬診斷結果！",
    subtitle: "留下聯繫方式，獲取完整報價單與限時優惠",
    emailPlaceholder: "您的 Email",
    linePlaceholder: "或填寫 LINE ID",
    ctaText: "獲取我的專屬報價",
    skipText: "先看結果，稍後再填",
    privacyNote: "我們尊重您的隱私，絕不濫發垃圾訊息。",
};
